version: '3'
services:
    zookeeper1:
        image: strimzi/kafka:latest-kafka-2.4.0
        hostname: zookeeper1
        command: [
            "sh", "-c",
            "bin/zookeeper-server-start.sh config/zookeeper.properties"
        ]
        ports:
            - "2181:2181"
        environment:
            - ZOO_MY_ID=1
            - ZOO_PORT=2181
            - ZOO_SERVERS=server.1=zookeeper1:2888:3888,server.2=zookeeper2:2888:3888
            - ALLOW_ANONYMOUS_LOGIN=yes
            - LOG_DIR=/tmp/logs
        volumes:
            - ./zookeeper1/data:/data
            - ./zookeeper1/datalog:/datalog
    zookeeper2:
        image: strimzi/kafka:latest-kafka-2.4.0
        hostname: zookeeper2
        command: [
            "sh", "-c",
            "bin/zookeeper-server-start.sh config/zookeeper.properties"
        ]
        ports:
            - "2182:2182"
        environment:
            - ZOO_MY_ID=2
            - ZOO_PORT=2182
            - ZOO_SERVERS=server.1=zookeeper1:2888:3888,server.2=zookeeper2:2888:3888
            - ALLOW_ANONYMOUS_LOGIN=yes
            - LOG_DIR=/tmp/logs
        volumes:
            - ./zookeeper2/data:/data
            - ./zookeeper2/datalog:/datalog
    kafka1:
        image: strimzi/kafka:latest-kafka-2.4.0
        hostname: kafka1
        command: [
        "sh", "-c",
        "bin/kafka-server-start.sh config/server.properties --override broker.id=$${KAFKA_BROKER_ID} --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT} --override listener.security.protocol.map=$${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP} --override inter.broker.listener.name=$${KAFKA_INTER_BROKER_LISTENER_NAME}"
        ]
        ports:
            - "29092:29092"
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,EXTERNAL://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            ALLOW_PLAINTEXT_LISTENER: "yes"
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_LISTENERS: INTERNAL://kafka1:9092,EXTERNAL://kafka1:29092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182
            LOG_DIR: /tmp/logs
            KAFKA_BROKER_ID: 1
        volumes:
            - ./kafka1/data:/var/lib/kafka/data
            - /var/run/docker.sock:/var/run/docker.sock
            - .:/home          
        depends_on:
            - zookeeper1
            - zookeeper2
    kafka2:
        image: strimzi/kafka:latest-kafka-2.4.0
        hostname: kafka2
        command: [
        "sh", "-c",
        "bin/kafka-server-start.sh config/server.properties --override broker.id=$${KAFKA_BROKER_ID} --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT} --override listener.security.protocol.map=$${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP} --override inter.broker.listener.name=$${KAFKA_INTER_BROKER_LISTENER_NAME}"
        ]
        ports:
            - "29093:29093"
            - "9093:9093"
        environment:
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9093,EXTERNAL://localhost:29093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_LISTENERS: INTERNAL://kafka2:9093,EXTERNAL://kafka2:29093
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182
            LOG_DIR: /tmp/logs
            KAFKA_BROKER_ID: 2
        volumes:
            - ./kafka2/data:/var/lib/kafka/data
            - /var/run/docker.sock:/var/run/docker.sock
            - .:/home          
        depends_on:
            - zookeeper1
            - zookeeper2
    kafka3:
        image: strimzi/kafka:latest-kafka-2.4.0
        hostname: kafka3
        command: [
        "sh", "-c",
        "bin/kafka-server-start.sh config/server.properties --override broker.id=$${KAFKA_BROKER_ID} --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT} --override listener.security.protocol.map=$${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP} --override inter.broker.listener.name=$${KAFKA_INTER_BROKER_LISTENER_NAME}"
        ]
        ports:
            - "29094:29094"
            - "9094:9094"
        environment:
            KAFKA_LISTENERS: INTERNAL://kafka3:9094,EXTERNAL://kafka3:29094
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:9094,EXTERNAL://localhost:29094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182
            LOG_DIR: /tmp/logs
            KAFKA_BROKER_ID: 3
        volumes:
            - ./kafka3/data:/var/lib/kafka/data
            - /var/run/docker.sock:/var/run/docker.sock
            - .:/home          
        depends_on:
            - zookeeper1
            - zookeeper2
networks:
    default:
        external:
            name: kafkanet