FROM maven:3.6-jdk-11-slim AS build
LABEL maintainer="IBM Garage Solution Engineering"
COPY . /usr/
RUN mvn -f /usr/pom.xml clean package

FROM open-liberty:20.0.0.3-full-java8-openj9
COPY --chown=1001:0 src/main/liberty/config /config/

COPY  --chown=1001:0 --from=build /usr/target/*.war /config/apps
USER 1001
RUN configure.sh